[package]
name = "za2c"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.61"
stderrlog = "0.4.1"
za-prover = { path = "../../../prover" }
za-compiler = { path = "../../../compiler" }
