[workspace]
members = [
    "cli",
    "parser",   
    "compiler",
    "bigsnark",
    "interop",
    "prover"
]

exclude = [
    "binding/js/native",
    "binding/golang/native",
    "binding/flutter/cargo",
    "binding/python3/native"
]
