name: Audit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install audit
      run: cargo install cargo-audit
    - name: Run audit
      run: cargo audit
